# gitops/infra/monitoring/loki/values-prod.yaml
# Loki - Production Environment Override with S3

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
    storage:
      type: 's3'
      bucketNames:
        chunks: unbox-prod-data-apne2
        admin: unbox-prod-data-apne2
        ruler: unbox-prod-data-apne2
      s3:
        endpoint: s3.ap-northeast-2.amazonaws.com
        region: ap-northeast-2
        insecure: false
        s3ForcePathStyle: false
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

singleBinary:
  replicas: 2  # S3 사용 가능하므로 2개 이상 띄울 수 있음
  persistence:
    enabled: true
    size: 20Gi
    storageClassName: gp2
  
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  
  # AWS IAM Role 마운트 (EKS IRSA 사용)
  env:
    - name: AWS_REGION
      value: ap-northeast-2

# Prod: 캐시 활성화
chunksCache:
  enabled: true
  memcached:
    batch_size: 1024
    parallelism: 100
resultsCache:
  enabled: true
  memcached:
    batch_size: 1024
    parallelism: 100
