apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9092
              name: client
            - containerPort: 9093
              name: controller
          env:
            # 1. 기본 역할 설정
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            
            # 2. 리스너 및 주소 설정
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-0.kafka.unbox-infra.svc.cluster.local:9092"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            
            # 3. [핵심 수정] 단일 노드 환경을 위한 복제본 설정 (무한 로그 해결)
            # 소비자 오프셋 장부 복제본을 1개만 생성하도록 설정
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            # 트랜잭션 상태 로그 복제본을 1개만 생성하도록 설정
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            # 트랜잭션 최소 동기화 노드 수를 1개로 하향
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            # 자동 토픽 생성 시 복제본 1개로 생성 (테스트 편의성)
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}