apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unbox-dev-services
  namespace: argocd
  labels:
    env: dev
    bundle: services
spec:
  project: default
  source:
    repoURL: https://github.com/team4-coding-gamja/UNBOX-INFRA.git
    targetRevision: feat/ArgoCD-dev
    path: gitops/apps
    directory:
      recurse: true
      include: "*/application-dev.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true