apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unbox-infrastructure
  namespace: argocd
  labels:
    type: infrastructure
    bundle: infra
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # 애플리케이션보다 먼저 배포
spec:
  project: default
  source:
    repoURL: https://github.com/team4-coding-gamja/UNBOX-INFRA.git
    targetRevision: HEAD
    path: gitops/infra
    directory:
      recurse: true
      include: "*/application.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: 'Description'
      value: 'Infrastructure components (Linkerd, Kafka, Tempo, Prometheus, Grafana)'
    - name: 'Deployment Order'
      value: 'Wave 0: Linkerd → Wave 4: Kafka → Wave 5: Tempo → Wave 6: Prometheus + Grafana'
