apiVersion: v1
kind: Secret
metadata:
  name: argo-rollouts-notification-secret
  namespace: argo-rollouts
type: Opaque
stringData:
  discord-webhook-url: "DISCORD_WEBHOOK_URL_HERE"  # 실제 Discord Webhook URL로 교체
