grafana:
  adminPassword: "prom-operator"
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: unbox-prod
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:632941626317:certificate/4c82b25a-8b6f-4276-8e83-e78255d31b0f"
      alb.ingress.kubernetes.io/healthcheck-path: /login
      alb.ingress.kubernetes.io/success-codes: '200'
    hosts:
      - grafana.un-box.click
    path: /
  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki.monitoring:3100
      version: 1
      isDefault: false
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring:3100
      version: 1
      isDefault: false
