apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: parameter-store-injector
    spec:
      version: v1.0
      init:
        command: [sh, -c]
        args:
          - |
            echo "Initializing Parameter Store Injector..."
      generate:
        command: [sh, -c]
        args:
          - |
            # AWS CLI로 Parameter Store에서 ACM ARN 가져오기
            ACM_ARN=$(aws ssm get-parameter --name /unbox/dev/acm/certificate_arn --query 'Parameter.Value' --output text --region ap-northeast-2 2>/dev/null || echo "")
            
            if [ -z "$ACM_ARN" ]; then
              echo "Warning: Could not fetch ACM ARN from Parameter Store" >&2
              # Fallback to existing value in values.yaml
              ACM_ARN=$(grep 'certificateArn:' values.yaml | awk '{print $2}' | tr -d '"')
            fi
            
            echo "Using ACM ARN: $ACM_ARN" >&2
            
            # Helm template 실행 (ArgoCD가 전달한 values 파일들 사용)
            # ARGOCD_APP_PARAMETERS 환경변수에서 values 파일 목록 가져오기
            if [ -n "$ARGOCD_ENV_HELM_VALUES" ]; then
              # 환경변수로 전달된 values 파일들 사용
              helm template $ARGOCD_APP_NAME . \
                --include-crds \
                --namespace $ARGOCD_APP_NAMESPACE \
                -f values.yaml \
                -f ../apps/common-values-dev.yaml \
                -f ../apps/order/values.yaml \
                -f ../apps/order/values-dev.yaml \
                --set ingress.certificateArn="$ACM_ARN"
            else
              # 기본 values.yaml만 사용
              helm template $ARGOCD_APP_NAME . \
                --include-crds \
                --namespace $ARGOCD_APP_NAMESPACE \
                --set ingress.certificateArn="$ACM_ARN"
            fi
      discover:
        fileName: "Chart.yaml"
