apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-prod
  namespace: argocd
  labels:
    component: observability
    env: prod
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.12.2
    helm:
      releaseName: metrics-server
      values: |
        args:
          - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
          - --kubelet-use-node-status-port
          - --kubelet-insecure-tls
          - --metric-resolution=15s
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
